### ISSUE TITLE
IE11 crashes because of css crawling

### ISSUE THREAD

**Issue by jonerd** [anselmh/object-fit#31]
Unfortunately in my project your plugin causes IE11 to crash. My project contains a lot of css-files and since the plugin is crawling all css files it seems to overcharge the browser. Why is it necessary to browse the css, when the plugin is initialized with explicit options like selector: 'img' and fittype: 'cover'? Is there any way to prevent css crawling?

**Comment by anselmh** [comment]
Hi, i’m sorry this is causing trouble with your site. However, due to the inheritance feature of values in CSS it is necessary to parse the whole CSS. The selector you give is only to set the target but doesn’t limit the CSS parsing. It’s true that this is not ideal but to match the behavior of `object-fit` as expected this is necessary.

You could either try to minimize your CSS or, try to emulate the behavior of [object-fit with SVG](http://tympanus.net/codrops/css_reference/object-fit/).
